// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schnauzer.Data;

#nullable disable

namespace Schnauzer.Migrations
{
    [DbContext(typeof(SchnauzerDb))]
    [Migration("20250601052610_AddAbandonedGracePeriodOption")]
    partial class AddAbandonedGracePeriodOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schnauzer.Data.Models.Channel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PanelMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PreferredLocale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Schnauzer.Data.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<TimeSpan?>("AbandonedGracePeriod")
                        .HasColumnType("interval");

                    b.Property<decimal?>("AutoModLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<decimal[]>("AutomodRuleIds")
                        .HasColumnType("numeric(20,0)[]");

                    b.PrimitiveCollection<decimal[]>("CanOwnRoleIds")
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<decimal?>("CreateChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("DefaultLobbySize")
                        .HasColumnType("integer");

                    b.Property<bool?>("DenyDeafenedOwnership")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DenyMutedOwnership")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAutoModEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxLobbyCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLobbySize")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredLocale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Schnauzer.Data.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLocale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Schnauzer.Data.Models.Channel", b =>
                {
                    b.HasOne("Schnauzer.Data.Models.Guild", "Guild")
                        .WithMany("DynamicChannels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Schnauzer.Data.Models.Guild", b =>
                {
                    b.Navigation("DynamicChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
