name: Push Image to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
      - name: Build the Docker image
        working-directory: './src/Schnauzer'
        run: docker build . -t ghcr.io/aux/schnauzer:latest
      - name: Log in to GHCR
        uses: docker/login-action@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GHCR
        run: docker push ghcr.io/aux/schnauzer:latest
